export const PARTIES = ['DMK', 'AIADMK', 'TVK', 'BJP', 'NTK', 'INC', 'CPI', 'CPI(M)', 'ADMK', 'PMK', 'DMDK', 'PT', 'Others'];

export const PARTY_COLORS = {
  DMK: '#ef4444',
  AIADMK: '#3b82f6',
  ADMK: '#3b82f6',
  TVK: '#eab308',
  BJP: '#f97316',
  NTK: '#a855f7',
  INC: '#19AAED',
  CPI: '#e70d21',
  'CPI(M)': '#FF1D15',
  PMK: '#5D672B',
  DMDK: '#E6C018',
  PT: '#3377c5',
  Others: '#6b7280',
};

export const STATE_METADATA = {
  S22: { name: 'Tamil Nadu', seats: 234, majority: 118 },
  S03: { name: 'Assam', seats: 126, majority: 64 },
  S11: { name: 'Kerala', seats: 140, majority: 71 },
  U07: { name: 'Puducherry', seats: 30, majority: 16 },
};

export const INITIAL_CONSTITUENCIES = [
  { id: 1, name: "Gummidipoondi", candidate: "T.J. Govindarajan", party: "DMK", margin: 15405, rounds: 15, status: "Leading", district: "Thiruvallur" },
  { id: 2, name: "Ponneri", candidate: "Durai Chandrasekar", party: "INC", margin: 15054, rounds: 16, status: "Leading", district: "Thiruvallur" },
  { id: 3, name: "Tiruttani", candidate: "S. Chandran", party: "DMK", margin: 11479, rounds: 10, status: "Leading", district: "Thiruvallur" },
  { id: 4, name: "Thiruvallur", candidate: "V.G. Raajendran", party: "DMK", margin: 11982, rounds: 10, status: "Leading", district: "Thiruvallur" },
  { id: 5, name: "Poonamallee", candidate: "A. Krishnaswamy", party: "DMK", margin: 15004, rounds: 13, status: "Leading", district: "Thiruvallur" },
  { id: 6, name: "Avadi", candidate: "S.M. Nasar", party: "DMK", margin: 16419, rounds: 16, status: "Leading", district: "Thiruvallur" },
  { id: 7, name: "Maduravoyal", candidate: "K. Ganapathy", party: "DMK", margin: 10511, rounds: 11, status: "Leading", district: "Thiruvallur" },
  { id: 8, name: "Ambattur", candidate: "Joseph Samuel", party: "DMK", margin: 14811, rounds: 16, status: "Leading", district: "Thiruvallur" },
  { id: 9, name: "Madavaram", candidate: "S. Sudharsanam", party: "DMK", margin: 10764, rounds: 10, status: "Leading", district: "Thiruvallur" },
  { id: 10, name: "Thiruvottiyur", candidate: "K.P. Shankar", party: "DMK", margin: 16025, rounds: 10, status: "Leading", district: "Chennai" },
  { id: 11, name: "Dr. Radhakrishnan Nagar", candidate: "Ebenezer J. J.", party: "DMK", margin: 2053, rounds: 16, status: "Leading", district: "Chennai" },
  { id: 12, name: "Perambur", candidate: "R.D. Sekar", party: "DMK", margin: 4547, rounds: 16, status: "Leading", district: "Chennai" },
  { id: 13, name: "Kolathur", candidate: "M.K. Stalin", party: "DMK", margin: 8927, rounds: 15, status: "Leading", district: "Chennai" },
  { id: 14, name: "Villivakkam", candidate: "A. Vetriazhagan", party: "DMK", margin: 14374, rounds: 15, status: "Leading", district: "Chennai" },
  { id: 15, name: "Thiru-Vi-Ka-Nagar", candidate: "P. Sivakumar", party: "DMK", margin: 6608, rounds: 10, status: "Leading", district: "Chennai" },
  { id: 16, name: "Egmore", candidate: "I. Paranthamen", party: "DMK", margin: 11620, rounds: 13, status: "Leading", district: "Chennai" },
  { id: 17, name: "Royapuram", candidate: "Idream R. Murthy", party: "DMK", margin: 7764, rounds: 10, status: "Leading", district: "Chennai" },
  { id: 18, name: "Harbour", candidate: "P.K. Sekar Babu", party: "DMK", margin: 8262, rounds: 10, status: "Leading", district: "Chennai" },
  { id: 19, name: "Chepauk-Thiruvallikeni", candidate: "Udhayanidhi Stalin", party: "DMK", margin: 7110, rounds: 13, status: "Leading", district: "Chennai" },
  { id: 20, name: "Thousand Lights", candidate: "Dr. Ezhilan Naganathan", party: "DMK", margin: 6072, rounds: 12, status: "Leading", district: "Chennai" },
  { id: 21, name: "Anna Nagar", candidate: "M.K. Mohan", party: "DMK", margin: 11074, rounds: 14, status: "Leading", district: "Chennai" },
  { id: 22, name: "Virugampakkam", candidate: "A.M.V. Prabhakara Raja", party: "DMK", margin: 11949, rounds: 16, status: "Leading", district: "Chennai" },
  { id: 23, name: "Saidapet", candidate: "Ma. Subramanian", party: "DMK", margin: 12896, rounds: 14, status: "Leading", district: "Chennai" },
  { id: 24, name: "T. Nagar", candidate: "J. Karunanithi", party: "DMK", margin: 16238, rounds: 11, status: "Leading", district: "Chennai" },
  { id: 25, name: "Mylapore", candidate: "Dha. Velu", party: "DMK", margin: 7725, rounds: 16, status: "Leading", district: "Chennai" },
  { id: 26, name: "Velachery", candidate: "J.M.H. Aassan Maulaana", party: "INC", margin: 16986, rounds: 14, status: "Leading", district: "Chennai" },
  { id: 27, name: "Sholinganallur", candidate: "S. Aravind Ramesh", party: "DMK", margin: 8431, rounds: 12, status: "Leading", district: "Chennai" },
  { id: 28, name: "Alandur", candidate: "T.M. Anbarasan", party: "DMK", margin: 3310, rounds: 10, status: "Leading", district: "Chennai" },
  { id: 29, name: "Sriperumbudur", candidate: "K. Selvaperunthagai", party: "INC", margin: 15303, rounds: 17, status: "Leading", district: "Kancheepuram" },
  { id: 30, name: "Pallavaram", candidate: "I. Karunanithi", party: "DMK", margin: 3635, rounds: 16, status: "Leading", district: "Kancheepuram" },
  { id: 31, name: "Tambaram", candidate: "S.R. Raja", party: "DMK", margin: 15940, rounds: 10, status: "Leading", district: "Kancheepuram" },
  { id: 32, name: "Chengalpattu", candidate: "M. Varalakshmi", party: "DMK", margin: 3160, rounds: 10, status: "Leading", district: "Kancheepuram" },
  { id: 33, name: "Thiruporur", candidate: "S.S. Balaji", party: "VCK", margin: 12568, rounds: 10, status: "Leading", district: "Kancheepuram" },
  { id: 34, name: "Cheyyur", candidate: "Panaiyur Babu", party: "VCK", margin: 9697, rounds: 14, status: "Leading", district: "Kancheepuram" },
  { id: 35, name: "Madurantakam", candidate: "K. Maragatham", party: "AIADMK", margin: 13751, rounds: 11, status: "Leading", district: "Kancheepuram" },
  { id: 36, name: "Uthiramerur", candidate: "K. Sundar", party: "DMK", margin: 14237, rounds: 15, status: "Leading", district: "Kancheepuram" },
  { id: 37, name: "Kancheepuram", candidate: "C.V.M.P. Ezhilarasan", party: "DMK", margin: 9035, rounds: 12, status: "Leading", district: "Kancheepuram" },
  { id: 38, name: "Arakkonam", candidate: "S. Ravi", party: "AIADMK", margin: 2278, rounds: 16, status: "Leading", district: "Vellore" },
  { id: 39, name: "Sholingur", candidate: "A.M. Munirathinam", party: "INC", margin: 15446, rounds: 11, status: "Leading", district: "Vellore" },
  { id: 40, name: "Katpadi", candidate: "Duraimurugan", party: "DMK", margin: 13803, rounds: 17, status: "Leading", district: "Vellore" },
  { id: 41, name: "Ranipet", candidate: "R. Gandhi", party: "DMK", margin: 2965, rounds: 14, status: "Leading", district: "Vellore" },
  { id: 42, name: "Arcot", candidate: "J.L. Eswarappan", party: "DMK", margin: 14423, rounds: 10, status: "Leading", district: "Vellore" },
  { id: 43, name: "Vellore", candidate: "P. Karthikeyan", party: "DMK", margin: 16215, rounds: 16, status: "Leading", district: "Vellore" },
  { id: 44, name: "Anaikattu", candidate: "A.P. Nandakumar", party: "DMK", margin: 2460, rounds: 14, status: "Leading", district: "Vellore" },
  { id: 45, name: "Kilvaithinankuppam", candidate: "G. Pon", party: "AIADMK", margin: 4839, rounds: 11, status: "Leading", district: "Vellore" },
  { id: 46, name: "Gudiyatham", candidate: "V. Amulu", party: "DMK", margin: 15691, rounds: 14, status: "Leading", district: "Vellore" },
  { id: 47, name: "Vaniyambadi", candidate: "G. Sendhil Kumar", party: "AIADMK", margin: 14276, rounds: 17, status: "Leading", district: "Vellore" },
  { id: 48, name: "Ambur", candidate: "A.C. Vilwanathan", party: "DMK", margin: 14777, rounds: 13, status: "Leading", district: "Vellore" },
  { id: 49, name: "Jolarpet", candidate: "K. Devaraji", party: "DMK", margin: 10187, rounds: 14, status: "Leading", district: "Vellore" },
  { id: 50, name: "Tirupattur", candidate: "A. Nallathambi", party: "DMK", margin: 14883, rounds: 17, status: "Leading", district: "Vellore" },
  { id: 51, name: "Uthangarai", candidate: "T.M. Tamilselvam", party: "AIADMK", margin: 14210, rounds: 15, status: "Leading", district: "Krishnagiri" },
  { id: 52, name: "Bargur", candidate: "D. Mathiazhagan", party: "DMK", margin: 3546, rounds: 14, status: "Leading", district: "Krishnagiri" },
  { id: 53, name: "Krishnagiri", candidate: "K. Ashok Kumar", party: "AIADMK", margin: 9696, rounds: 11, status: "Leading", district: "Krishnagiri" },
  { id: 54, name: "Veppanahalli", candidate: "K.P. Munusamy", party: "AIADMK", margin: 6958, rounds: 13, status: "Leading", district: "Krishnagiri" },
  { id: 55, name: "Hosur", candidate: "Y. Prakaash", party: "DMK", margin: 15403, rounds: 15, status: "Leading", district: "Krishnagiri" },
  { id: 56, name: "Thalli", candidate: "T. Ramachandran", party: "CPI", margin: 15887, rounds: 15, status: "Leading", district: "Krishnagiri" },
  { id: 57, name: "Palacode", candidate: "K.P. Anbalagan", party: "AIADMK", margin: 13335, rounds: 11, status: "Leading", district: "Dharmapuri" },
  { id: 58, name: "Pennagaram", candidate: "G.K. Mani", party: "PMK", margin: 5674, rounds: 17, status: "Leading", district: "Dharmapuri" },
  { id: 59, name: "Dharmapuri", candidate: "S.P. Venkateshwaran", party: "PMK", margin: 12627, rounds: 16, status: "Leading", district: "Dharmapuri" },
  { id: 60, name: "Pappireddipatti", candidate: "A. Govindasamy", party: "AIADMK", margin: 14698, rounds: 17, status: "Leading", district: "Dharmapuri" },
  { id: 61, name: "Harur", candidate: "V. Sampathkumar", party: "AIADMK", margin: 9174, rounds: 13, status: "Leading", district: "Dharmapuri" },
  { id: 62, name: "Chengam", candidate: "M.P. Giri", party: "DMK", margin: 5491, rounds: 11, status: "Leading", district: "Tiruvannamalai" },
  { id: 63, name: "Tiruvannamalai", candidate: "E.V. Velu", party: "DMK", margin: 16739, rounds: 12, status: "Leading", district: "Tiruvannamalai" },
  { id: 64, name: "Kilpennathur", candidate: "K. Pitchandi", party: "DMK", margin: 11406, rounds: 14, status: "Leading", district: "Tiruvannamalai" },
  { id: 65, name: "Kalasapakkam", candidate: "P.S.T. Saravanan", party: "DMK", margin: 12398, rounds: 11, status: "Leading", district: "Tiruvannamalai" },
  { id: 66, name: "Polur", candidate: "Agri S.S. Krishnamurthy", party: "AIADMK", margin: 13737, rounds: 13, status: "Leading", district: "Tiruvannamalai" },
  { id: 67, name: "Arani", candidate: "Sevvoor S. Ramachandran", party: "AIADMK", margin: 6173, rounds: 12, status: "Leading", district: "Tiruvannamalai" },
  { id: 68, name: "Cheyyar", candidate: "O. Jothi", party: "DMK", margin: 16440, rounds: 17, status: "Leading", district: "Tiruvannamalai" },
  { id: 69, name: "Vandavasi", candidate: "S. Ambethkumar", party: "DMK", margin: 4619, rounds: 15, status: "Leading", district: "Tiruvannamalai" },
  { id: 70, name: "Gingee", candidate: "K.S. Masthan", party: "DMK", margin: 16797, rounds: 12, status: "Leading", district: "Villupuram" },
  { id: 71, name: "Mailam", candidate: "C. Sivakumar", party: "PMK", margin: 5747, rounds: 14, status: "Leading", district: "Villupuram" },
  { id: 72, name: "Tindivanam", candidate: "P. Arjunan", party: "AIADMK", margin: 6721, rounds: 14, status: "Leading", district: "Villupuram" },
  { id: 73, name: "Vanur", candidate: "M. Chakrapani", party: "AIADMK", margin: 8911, rounds: 17, status: "Leading", district: "Villupuram" },
  { id: 74, name: "Villupuram", candidate: "R. Lakshmanan", party: "DMK", margin: 14159, rounds: 17, status: "Leading", district: "Villupuram" },
  { id: 75, name: "Vikravandi", candidate: "N. Pugazhenthi", party: "DMK", margin: 12536, rounds: 10, status: "Leading", district: "Villupuram" },
  { id: 76, name: "Tirukkoyilur", candidate: "K. Ponmudy", party: "DMK", margin: 11959, rounds: 10, status: "Leading", district: "Villupuram" },
  { id: 77, name: "Ulundurpettai", candidate: "A.J. Manikannan", party: "DMK", margin: 13631, rounds: 14, status: "Leading", district: "Villupuram" },
  { id: 78, name: "Rishivandiyam", candidate: "K. Karthikeyan", party: "DMK", margin: 7942, rounds: 15, status: "Leading", district: "Villupuram" },
  { id: 79, name: "Sankarapuram", candidate: "T. Udhayasuriyan", party: "DMK", margin: 14252, rounds: 12, status: "Leading", district: "Villupuram" },
  { id: 80, name: "Kallakurichi", candidate: "M. Senthilkumar", party: "AIADMK", margin: 16317, rounds: 17, status: "Leading", district: "Villupuram" },
  { id: 81, name: "Gangavalli", candidate: "A. Nallathambi", party: "AIADMK", margin: 5465, rounds: 10, status: "Leading", district: "Salem" },
  { id: 82, name: "Attur", candidate: "Jayashankaran", party: "AIADMK", margin: 8622, rounds: 10, status: "Leading", district: "Salem" },
  { id: 83, name: "Yercaud", candidate: "G. Chitra", party: "AIADMK", margin: 2646, rounds: 14, status: "Leading", district: "Salem" },
  { id: 84, name: "Omalur", candidate: "R. Mani", party: "AIADMK", margin: 9813, rounds: 15, status: "Leading", district: "Salem" },
  { id: 85, name: "Mettur", candidate: "S. Sadhasivam", party: "PMK", margin: 14093, rounds: 11, status: "Leading", district: "Salem" },
  { id: 86, name: "Edappadi", candidate: "Edappadi K. Palaniswami", party: "AIADMK", margin: 10491, rounds: 14, status: "Leading", district: "Salem" },
  { id: 87, name: "Sankari", candidate: "S. Sundararajan", party: "AIADMK", margin: 2804, rounds: 12, status: "Leading", district: "Salem" },
  { id: 88, name: "Salem West", candidate: "R. Arul", party: "PMK", margin: 7524, rounds: 14, status: "Leading", district: "Salem" },
  { id: 89, name: "Salem North", candidate: "R. Rajendran", party: "DMK", margin: 8085, rounds: 10, status: "Leading", district: "Salem" },
  { id: 90, name: "Salem South", candidate: "E. Balasubramanian", party: "AIADMK", margin: 7880, rounds: 12, status: "Leading", district: "Salem" },
  { id: 91, name: "Veerapandi", candidate: "M. Rajasekaran", party: "AIADMK", margin: 11766, rounds: 11, status: "Leading", district: "Salem" },
  { id: 92, name: "Rasipuram", candidate: "Dr. M. Mathiventhan", party: "DMK", margin: 6017, rounds: 17, status: "Leading", district: "Namakkal" },
  { id: 93, name: "Senthamangalam", candidate: "K. Ponnusamy", party: "DMK", margin: 5060, rounds: 17, status: "Leading", district: "Namakkal" },
  { id: 94, name: "Namakkal", candidate: "P. Ramalingam", party: "DMK", margin: 2176, rounds: 16, status: "Leading", district: "Namakkal" },
  { id: 95, name: "Paramathi-Velur", candidate: "S. Anbalagan", party: "AIADMK", margin: 9562, rounds: 12, status: "Leading", district: "Namakkal" },
  { id: 96, name: "Tiruchengode", candidate: "E.R. Eswaran", party: "KMDK", margin: 11964, rounds: 14, status: "Leading", district: "Namakkal" },
  { id: 97, name: "Kumarapalayam", candidate: "P. Thangamani", party: "AIADMK", margin: 6438, rounds: 15, status: "Leading", district: "Namakkal" },
  { id: 98, name: "Erode East", candidate: "E.V.K.S. Elangovan", party: "INC", margin: 4063, rounds: 14, status: "Leading", district: "Erode" },
  { id: 99, name: "Erode West", candidate: "S. Muthusamy", party: "DMK", margin: 13427, rounds: 11, status: "Leading", district: "Erode" },
  { id: 100, name: "Modakkurichi", candidate: "C. Saraswathi", party: "BJP", margin: 12428, rounds: 14, status: "Leading", district: "Erode" },
  { id: 101, name: "Dharapuram", candidate: "N. Kayalvizhi", party: "DMK", margin: 12306, rounds: 14, status: "Leading", district: "Erode" },
  { id: 102, name: "Kangayam", candidate: "M.P. Saminathan", party: "DMK", margin: 12177, rounds: 12, status: "Leading", district: "Erode" },
  { id: 103, name: "Perundurai", candidate: "S. Jayakumar", party: "AIADMK", margin: 3522, rounds: 15, status: "Leading", district: "Erode" },
  { id: 104, name: "Bhavani", candidate: "K.C. Karuppannan", party: "AIADMK", margin: 4091, rounds: 16, status: "Leading", district: "Erode" },
  { id: 105, name: "Anthiyur", candidate: "A.G. Venkatachalam", party: "DMK", margin: 12012, rounds: 14, status: "Leading", district: "Erode" },
  { id: 106, name: "Gobichettipalayam", candidate: "K.A. Sengottaiyan", party: "AIADMK", margin: 5574, rounds: 17, status: "Leading", district: "Erode" },
  { id: 107, name: "Bhavanisagar", candidate: "A. Bannari", party: "AIADMK", margin: 9865, rounds: 10, status: "Leading", district: "Erode" },
  { id: 108, name: "Udhagamandalam", candidate: "R. Ganesh", party: "INC", margin: 7982, rounds: 16, status: "Leading", district: "Nilgiris" },
  { id: 109, name: "Gudalur", candidate: "Pon. Jayaseelan", party: "AIADMK", margin: 2247, rounds: 11, status: "Leading", district: "Nilgiris" },
  { id: 110, name: "Coonoor", candidate: "K. Ramachandran", party: "DMK", margin: 12245, rounds: 16, status: "Leading", district: "Nilgiris" },
  { id: 111, name: "Mettupalayam", candidate: "A.K. Selvaraj", party: "AIADMK", margin: 8020, rounds: 16, status: "Leading", district: "Coimbatore" },
  { id: 112, name: "Avanashi", candidate: "P. Dhanapal", party: "AIADMK", margin: 7580, rounds: 13, status: "Leading", district: "Coimbatore" },
  { id: 113, name: "Tiruppur North", candidate: "K.N. Vijeyakumar", party: "AIADMK", margin: 12202, rounds: 12, status: "Leading", district: "Coimbatore" },
  { id: 114, name: "Tiruppur South", candidate: "K. Selvaraj", party: "DMK", margin: 3885, rounds: 11, status: "Leading", district: "Coimbatore" },
  { id: 115, name: "Palladam", candidate: "M.S.M. Anandan", party: "AIADMK", margin: 11830, rounds: 13, status: "Leading", district: "Coimbatore" },
  { id: 116, name: "Sulur", candidate: "V.P. Kandasamy", party: "AIADMK", margin: 11570, rounds: 13, status: "Leading", district: "Coimbatore" },
  { id: 117, name: "Kavundampalayam", candidate: "G. Arunkumar", party: "AIADMK", margin: 4517, rounds: 14, status: "Leading", district: "Coimbatore" },
  { id: 118, name: "Coimbatore North", candidate: "Amman K. Arjunan", party: "AIADMK", margin: 8039, rounds: 14, status: "Leading", district: "Coimbatore" },
  { id: 119, name: "Thondamuthur", candidate: "S.P. Velumani", party: "AIADMK", margin: 6640, rounds: 16, status: "Leading", district: "Coimbatore" },
  { id: 120, name: "Coimbatore South", candidate: "Vanathi Srinivasan", party: "BJP", margin: 2790, rounds: 14, status: "Leading", district: "Coimbatore" },
  { id: 121, name: "Singanallur", candidate: "K.R. Jayaram", party: "AIADMK", margin: 10534, rounds: 10, status: "Leading", district: "Coimbatore" },
  { id: 122, name: "Kinathukadavu", candidate: "S. Damodaran", party: "AIADMK", margin: 6131, rounds: 14, status: "Leading", district: "Coimbatore" },
  { id: 123, name: "Pollachi", candidate: "Pollachi V. Jayaraman", party: "AIADMK", margin: 12129, rounds: 14, status: "Leading", district: "Coimbatore" },
  { id: 124, name: "Valparai", candidate: "Amul Kandasamy", party: "AIADMK", margin: 7205, rounds: 14, status: "Leading", district: "Coimbatore" },
  { id: 125, name: "Udumalaipettai", candidate: "K. Radhakrishnan", party: "AIADMK", margin: 12966, rounds: 12, status: "Leading", district: "Tiruppur" },
  { id: 126, name: "Madathukulam", candidate: "C. Mahendran", party: "AIADMK", margin: 3267, rounds: 15, status: "Leading", district: "Tiruppur" },
  { id: 127, name: "Palani", candidate: "I.P. Senthil Kumar", party: "DMK", margin: 5877, rounds: 13, status: "Leading", district: "Dindigul" },
  { id: 128, name: "Oddanchatram", candidate: "R. Sakkarapani", party: "DMK", margin: 2262, rounds: 13, status: "Leading", district: "Dindigul" },
  { id: 129, name: "Athoor", candidate: "I. Periyasamy", party: "DMK", margin: 12515, rounds: 14, status: "Leading", district: "Dindigul" },
  { id: 130, name: "Nilakottai", candidate: "S. Thenmozhi", party: "AIADMK", margin: 10393, rounds: 12, status: "Leading", district: "Dindigul" },
  { id: 131, name: "Natham", candidate: "M.A. Andi Ambalam", party: "DMK", margin: 6387, rounds: 10, status: "Leading", district: "Dindigul" },
  { id: 132, name: "Dindigul", candidate: "C. Sreenivasan", party: "AIADMK", margin: 5194, rounds: 15, status: "Leading", district: "Dindigul" },
  { id: 133, name: "Vedasandur", candidate: "S. Gandhirajan", party: "DMK", margin: 13182, rounds: 14, status: "Leading", district: "Dindigul" },
  { id: 134, name: "Aravakurichi", candidate: "R. Elango", party: "DMK", margin: 7419, rounds: 10, status: "Leading", district: "Karur" },
  { id: 135, name: "Karur", candidate: "V. Senthil Balaji", party: "DMK", margin: 4098, rounds: 13, status: "Leading", district: "Karur" },
  { id: 136, name: "Krishnarayapuram", candidate: "K. Sivagamasundari", party: "DMK", margin: 6649, rounds: 12, status: "Leading", district: "Karur" },
  { id: 137, name: "Kulithalai", candidate: "R. Manickam", party: "DMK", margin: 9695, rounds: 10, status: "Leading", district: "Karur" },
  { id: 138, name: "Manapparai", candidate: "P. Abdul Samad", party: "DMK", margin: 2976, rounds: 16, status: "Leading", district: "Trichy" },
  { id: 139, name: "Srirangam", candidate: "M. Palaniyandi", party: "DMK", margin: 12607, rounds: 17, status: "Leading", district: "Trichy" },
  { id: 140, name: "Tiruchirappalli West", candidate: "K.N. Nehru", party: "DMK", margin: 13149, rounds: 16, status: "Leading", district: "Trichy" },
  { id: 141, name: "Tiruchirappalli East", candidate: "Inigo Irudayanath S", party: "DMK", margin: 11432, rounds: 16, status: "Leading", district: "Trichy" },
  { id: 142, name: "Thiruverumbur", candidate: "Anbil Mahesh Poyyamozhi", party: "DMK", margin: 3485, rounds: 13, status: "Leading", district: "Trichy" },
  { id: 143, name: "Lalgudi", candidate: "A. Soundarapandian", party: "DMK", margin: 9341, rounds: 15, status: "Leading", district: "Trichy" },
  { id: 144, name: "Manachanallur", candidate: "S. Kathiravan", party: "DMK", margin: 7659, rounds: 15, status: "Leading", district: "Trichy" },
  { id: 145, name: "Musiri", candidate: "N. Thiyagarajan", party: "DMK", margin: 5101, rounds: 12, status: "Leading", district: "Trichy" },
  { id: 146, name: "Thuraiyur", candidate: "S. Stalinkumar", party: "DMK", margin: 3452, rounds: 15, status: "Leading", district: "Trichy" },
  { id: 147, name: "Perambalur", candidate: "M. Prabhakaran", party: "DMK", margin: 10550, rounds: 17, status: "Leading", district: "Perambalur" },
  { id: 148, name: "Kunnam", candidate: "S.S. Sivasankar", party: "DMK", margin: 7303, rounds: 12, status: "Leading", district: "Perambalur" },
  { id: 149, name: "Ariyalur", candidate: "K. Chinnappa", party: "DMK", margin: 13446, rounds: 17, status: "Leading", district: "Ariyalur" },
  { id: 150, name: "Jayankondam", candidate: "K. Kannan", party: "DMK", margin: 12767, rounds: 12, status: "Leading", district: "Ariyalur" },
  { id: 151, name: "Tittakudi", candidate: "C.V. Ganesan", party: "DMK", margin: 10968, rounds: 10, status: "Leading", district: "Cuddalore" },
  { id: 152, name: "Vriddhachalam", candidate: "R. Radhakrishnan", party: "INC", margin: 8568, rounds: 17, status: "Leading", district: "Cuddalore" },
  { id: 153, name: "Neyveli", candidate: "Saba Rajendran", party: "DMK", margin: 6206, rounds: 14, status: "Leading", district: "Cuddalore" },
  { id: 154, name: "Panruti", candidate: "T. Velmurugan", party: "TVK", margin: 8636, rounds: 17, status: "Leading", district: "Cuddalore" },
  { id: 155, name: "Cuddalore", candidate: "G. Iyappan", party: "DMK", margin: 7382, rounds: 11, status: "Leading", district: "Cuddalore" },
  { id: 156, name: "Kurinjipadi", candidate: "M.R.K. Panneerselvam", party: "DMK", margin: 6870, rounds: 10, status: "Leading", district: "Cuddalore" },
  { id: 157, name: "Bhuvanagiri", candidate: "A. Kathiravan", party: "DMK", margin: 7517, rounds: 11, status: "Leading", district: "Cuddalore" },
  { id: 158, name: "Chidambaram", candidate: "K.A. Pandian", party: "AIADMK", margin: 13003, rounds: 10, status: "Leading", district: "Cuddalore" },
  { id: 159, name: "Kattumannarkoil", candidate: "Sinthanai Selvan", party: "VCK", margin: 7548, rounds: 17, status: "Leading", district: "Cuddalore" },
  { id: 160, name: "Sirkazhi", candidate: "M. Panneerselvam", party: "DMK", margin: 3783, rounds: 16, status: "Leading", district: "Nagapattinam" },
  { id: 161, name: "Mayiladuthurai", candidate: "S. Rajakumar", party: "INC", margin: 7604, rounds: 14, status: "Leading", district: "Nagapattinam" },
  { id: 162, name: "Poompuhar", candidate: "Nivetha M. Murugan", party: "DMK", margin: 5764, rounds: 16, status: "Leading", district: "Nagapattinam" },
  { id: 163, name: "Nagapattinam", candidate: "Aaloor Sha Navas", party: "VCK", margin: 3923, rounds: 14, status: "Leading", district: "Nagapattinam" },
  { id: 164, name: "Kilvelur", candidate: "Nagai Mali", party: "CPI(M)", margin: 1481, rounds: 17, status: "Leading", district: "Nagapattinam" },
  { id: 165, name: "Vedaranyam", candidate: "O.S. Manian", party: "AIADMK", margin: 6980, rounds: 16, status: "Leading", district: "Nagapattinam" },
  { id: 166, name: "Thiruthuraipoondi", candidate: "K. Marimuthu", party: "CPI", margin: 1121, rounds: 14, status: "Leading", district: "Tiruvarur" },
  { id: 167, name: "Mannargudi", candidate: "T.R.B. Rajaa", party: "DMK", margin: 5891, rounds: 16, status: "Leading", district: "Tiruvarur" },
  { id: 168, name: "Thiruvarur", candidate: "K. Poondi Kalaivanan", party: "DMK", margin: 4923, rounds: 10, status: "Leading", district: "Tiruvarur" },
  { id: 169, name: "Nannilam", candidate: "S. Kamaraj", party: "AIADMK", margin: 6435, rounds: 13, status: "Leading", district: "Tiruvarur" },
  { id: 170, name: "Thiruvaiyaru", candidate: "Durai Chandrasekaran", party: "DMK", margin: 6068, rounds: 12, status: "Leading", district: "Thanjavur" },
  { id: 171, name: "Thanjavur", candidate: "T.K.G. Neelamegam", party: "DMK", margin: 8397, rounds: 17, status: "Leading", district: "Thanjavur" },
  { id: 172, name: "Orathanadu", candidate: "R. Vaithilingam", party: "AIADMK", margin: 4452, rounds: 12, status: "Leading", district: "Thanjavur" },
  { id: 173, name: "Pattukkottai", candidate: "K. Annadurai", party: "DMK", margin: 3302, rounds: 15, status: "Leading", district: "Thanjavur" },
  { id: 174, name: "Peravurani", candidate: "N. Ashok Kumar", party: "DMK", margin: 896, rounds: 12, status: "Leading", district: "Thanjavur" },
  { id: 175, name: "Gandharvakottai", candidate: "M. Chinnadurai", party: "CPI(M)", margin: 1753, rounds: 17, status: "Leading", district: "Pudukkottai" },
  { id: 176, name: "Viralimalai", candidate: "C. Vijayabaskar", party: "AIADMK", margin: 5912, rounds: 13, status: "Leading", district: "Pudukkottai" },
  { id: 177, name: "Pudukkottai", candidate: "Dr. Muthuraja V", party: "DMK", margin: 8146, rounds: 12, status: "Leading", district: "Pudukkottai" },
  { id: 178, name: "Thirumayam", candidate: "S. Regupathy", party: "DMK", margin: 2710, rounds: 16, status: "Leading", district: "Pudukkottai" },
  { id: 179, name: "Alangudi", candidate: "Meyyanathan Siva V", party: "DMK", margin: 1251, rounds: 16, status: "Leading", district: "Pudukkottai" },
  { id: 180, name: "Aranthangi", candidate: "T. Ramachandran", party: "INC", margin: 8452, rounds: 14, status: "Leading", district: "Pudukkottai" },
  { id: 181, name: "Karaikudi", candidate: "S. Mangudi", party: "INC", margin: 4884, rounds: 13, status: "Leading", district: "Sivagangai" },
  { id: 182, name: "Tiruppattur", candidate: "K.R. Periakaruppan", party: "DMK", margin: 5277, rounds: 12, status: "Leading", district: "Sivagangai" },
  { id: 183, name: "Sivagangai", candidate: "P.R. Senthilnathan", party: "AIADMK", margin: 1984, rounds: 17, status: "Leading", district: "Sivagangai" },
  { id: 184, name: "Manamadurai", candidate: "A. Tamilarasi", party: "DMK", margin: 3884, rounds: 13, status: "Leading", district: "Sivagangai" },
  { id: 185, name: "Melur", candidate: "P. Selvam", party: "AIADMK", margin: 1915, rounds: 12, status: "Leading", district: "Madurai" },
  { id: 186, name: "Madurai East", candidate: "P. Moorthy", party: "DMK", margin: 2593, rounds: 16, status: "Leading", district: "Madurai" },
  { id: 187, name: "Sholavandan", candidate: "A. Venkatesan", party: "DMK", margin: 6079, rounds: 13, status: "Leading", district: "Madurai" },
  { id: 188, name: "Madurai North", candidate: "G. Thalapathi", party: "DMK", margin: 6665, rounds: 15, status: "Leading", district: "Madurai" },
  { id: 189, name: "Madurai South", candidate: "M. Boominathan", party: "MDMK", margin: 1712, rounds: 15, status: "Leading", district: "Madurai" },
  { id: 190, name: "Madurai Central", candidate: "Palani Vel Thiagarajan", party: "DMK", margin: 8448, rounds: 16, status: "Leading", district: "Madurai" },
  { id: 191, name: "Madurai West", candidate: "Sellur K. Raju", party: "AIADMK", margin: 3665, rounds: 15, status: "Leading", district: "Madurai" },
  { id: 192, name: "Thiruparankundram", candidate: "V.V. Rajan Chellappa", party: "AIADMK", margin: 8057, rounds: 17, status: "Leading", district: "Madurai" },
  { id: 193, name: "Thirumangalam", candidate: "R.B. Udhayakumar", party: "AIADMK", margin: 3178, rounds: 15, status: "Leading", district: "Madurai" },
  { id: 194, name: "Usilampatti", candidate: "P. Ayyappan", party: "AIADMK", margin: 1401, rounds: 10, status: "Leading", district: "Madurai" },
  { id: 195, name: "Andipatti", candidate: "A. Maharajan", party: "DMK", margin: 3702, rounds: 17, status: "Leading", district: "Theni" },
  { id: 196, name: "Periyakulam", candidate: "K.S. Saravana Kumar", party: "DMK", margin: 4235, rounds: 16, status: "Leading", district: "Theni" },
  { id: 197, name: "Bodinayakanur", candidate: "O. Panneerselvam", party: "AIADMK", margin: 8684, rounds: 17, status: "Leading", district: "Theni" },
  { id: 198, name: "Cumbum", candidate: "N. Eramakrishnan", party: "DMK", margin: 4556, rounds: 17, status: "Leading", district: "Theni" },
  { id: 199, name: "Theni", candidate: "O. Panneerselvam", party: "AIADMK", margin: 3363, rounds: 16, status: "Leading", district: "Theni" },
  { id: 200, name: "Rajapalayam", candidate: "S. Thangappandian", party: "DMK", margin: 2127, rounds: 17, status: "Leading", district: "Virudhunagar" },
  { id: 201, name: "Srivilliputhur", candidate: "E.M. Manraj", party: "AIADMK", margin: 2590, rounds: 14, status: "Leading", district: "Virudhunagar" },
  { id: 202, name: "Sattur", candidate: "A.R.R. Raghuraman", party: "DMK", margin: 4334, rounds: 16, status: "Leading", district: "Virudhunagar" },
  { id: 203, name: "Sivakasi", candidate: "G. Ashokan", party: "INC", margin: 5244, rounds: 15, status: "Leading", district: "Virudhunagar" },
  { id: 204, name: "Virudhunagar", candidate: "A.R.R. Seenivasan", party: "DMK", margin: 587, rounds: 17, status: "Leading", district: "Virudhunagar" },
  { id: 205, name: "Aruppukottai", candidate: "K.K.S.S.R. Ramachandran", party: "DMK", margin: 2839, rounds: 12, status: "Leading", district: "Virudhunagar" },
  { id: 206, name: "Tiruchuli", candidate: "Thangam Thennarasu", party: "DMK", margin: 5407, rounds: 11, status: "Leading", district: "Virudhunagar" },
  { id: 207, name: "Paramakudi", candidate: "S. Murugesan", party: "DMK", margin: 2005, rounds: 11, status: "Leading", district: "Ramanathapuram" },
  { id: 208, name: "Tiruvadanai", candidate: "R.M. Karumanickam", party: "INC", margin: 3541, rounds: 12, status: "Leading", district: "Ramanathapuram" },
  { id: 209, name: "Ramanathapuram", candidate: "Katharbatcha Muthuramalingam", party: "DMK", margin: 2967, rounds: 17, status: "Leading", district: "Ramanathapuram" },
  { id: 210, name: "Mudhukulathur", candidate: "R.S. Raja Kannappan", party: "DMK", margin: 5154, rounds: 17, status: "Leading", district: "Ramanathapuram" },
  { id: 211, name: "Vilathikulam", candidate: "G.V. Markandayan", party: "DMK", margin: 973, rounds: 14, status: "Leading", district: "Thoothukudi" },
  { id: 212, name: "Thoothukudi", candidate: "P. Geetha Jeevan", party: "DMK", margin: 1005, rounds: 13, status: "Leading", district: "Thoothukudi" },
  { id: 213, name: "Tiruchendur", candidate: "Anitha R. Radhakrishnan", party: "DMK", margin: 4851, rounds: 10, status: "Leading", district: "Thoothukudi" },
  { id: 214, name: "Srivaikuntam", candidate: "G. Urkavalan", party: "INC", margin: 907, rounds: 15, status: "Leading", district: "Thoothukudi" },
  { id: 215, name: "Ottapidaram", candidate: "M.C. Shunmugaiah", party: "DMK", margin: 2213, rounds: 13, status: "Leading", district: "Thoothukudi" },
  { id: 216, name: "Kovilpatti", candidate: "Kadambur C. Raju", party: "AIADMK", margin: 3983, rounds: 12, status: "Leading", district: "Thoothukudi" },
  { id: 217, name: "Sankarankovil", candidate: "E. Raja", party: "DMK", margin: 3953, rounds: 13, status: "Leading", district: "Tirunelveli" },
  { id: 218, name: "Vasudevanallur", candidate: "Dr. T. Sathan Thirumalaikumar", party: "MDMK", margin: 1078, rounds: 16, status: "Leading", district: "Tirunelveli" },
  { id: 219, name: "Kadayanallur", candidate: "C. Krishnamurali", party: "AIADMK", margin: 434, rounds: 14, status: "Leading", district: "Tirunelveli" },
  { id: 220, name: "Tenkasi", candidate: "S. Palani Nadar", party: "INC", margin: 1876, rounds: 10, status: "Leading", district: "Tirunelveli" },
  { id: 221, name: "Alangulam", candidate: "P.H. Manoj Pandian", party: "AIADMK", margin: 1375, rounds: 16, status: "Leading", district: "Tirunelveli" },
  { id: 222, name: "Tirunelveli", candidate: "Nainar Nagenthran", party: "BJP", margin: 2327, rounds: 10, status: "Leading", district: "Tirunelveli" },
  { id: 223, name: "Ambasamudram", candidate: "E. Subaya", party: "AIADMK", margin: 695, rounds: 12, status: "Leading", district: "Tirunelveli" },
  { id: 224, name: "Palayamkottai", candidate: "M. Abdul Wahab", party: "DMK", margin: 3722, rounds: 13, status: "Leading", district: "Tirunelveli" },
  { id: 225, name: "Nanguneri", candidate: "Ruby R. Manoharan", party: "INC", margin: 2372, rounds: 12, status: "Leading", district: "Tirunelveli" },
  { id: 226, name: "Radhapuram", candidate: "M. Appavu", party: "DMK", margin: 3214, rounds: 12, status: "Leading", district: "Tirunelveli" },
  { id: 227, name: "Kanniyakumari", candidate: "N. Thalavai Sundaram", party: "AIADMK", margin: 2752, rounds: 15, status: "Leading", district: "Kanyakumari" },
  { id: 228, name: "Nagercoil", candidate: "M.R. Gandhi", party: "BJP", margin: 2062, rounds: 16, status: "Leading", district: "Kanyakumari" },
  { id: 229, name: "Colachel", candidate: "J.G. Prince", party: "INC", margin: 4018, rounds: 14, status: "Leading", district: "Kanyakumari" },
  { id: 230, name: "Padmanabhapuram", candidate: "Mano Thangaraj T", party: "DMK", margin: 956, rounds: 10, status: "Leading", district: "Kanyakumari" },
  { id: 231, name: "Vilavancode", candidate: "S. Vijayadharani", party: "INC", margin: 352, rounds: 11, status: "Leading", district: "Kanyakumari" },
  { id: 232, name: "Killiyoor", candidate: "S. Rajesh Kumar", party: "INC", margin: 4235, rounds: 16, status: "Leading", district: "Kanyakumari" },
  { id: 233, name: "Harbour", candidate: "P.K. Sekar Babu", party: "DMK", margin: 8684, rounds: 17, status: "Leading", district: "Chennai" },
  { id: 234, name: "Saidapet", candidate: "Ma. Subramanian", party: "DMK", margin: 4556, rounds: 17, status: "Leading", district: "Chennai" },
];
