export const PARTIES = ['DMK', 'AIADMK', 'TVK', 'BJP', 'NTK', 'Others'];

export const PARTY_COLORS = {
  DMK: '#ef4444',
  AIADMK: '#3b82f6',
  TVK: '#eab308',
  BJP: '#f97316',
  NTK: '#a855f7',
  Others: '#6b7280',
};

export const INITIAL_CONSTITUENCIES = [
  { name: "Srirangam", candidate: "M.K. Stalin", party: "DMK", margin: 15004, rounds: 13, status: "Tight Fight", district: "Trichy" },
  { name: "Chennai Central", candidate: "Udhayanidhi Stalin", party: "DMK", margin: 11982, rounds: 10, status: "Won", district: "Chennai" },
  { name: "Thousand Lights", candidate: "K.N. Nehru", party: "DMK", margin: 11479, rounds: 10, status: "Tight Fight", district: "Chennai" },
  { name: "Ambur", candidate: "Duraimurugan", party: "DMK", margin: 15405, rounds: 15, status: "Tight Fight", district: "Vellore" },
  { name: "Kumbakonam", candidate: "A. Raja", party: "DMK", margin: 15054, rounds: 16, status: "Won", district: "Thanjavur" },
  { name: "Attur", candidate: "T.R. Baalu", party: "DMK", margin: 16419, rounds: 16, status: "Leading", district: "Salem" },
  { name: "Chennai South", candidate: "Kanimozhi", party: "DMK", margin: 10511, rounds: 11, status: "Leading", district: "Chennai" },
  { name: "Thiruvarur", candidate: "P.T.R. Palanivel Thiagarajan", party: "DMK", margin: 14811, rounds: 16, status: "Leading", district: "Thanjavur" },
  { name: "Thirukkuvalai", candidate: "S. Muthusamy", party: "DMK", margin: 10764, rounds: 10, status: "Won", district: "Thanjavur" },
  { name: "Constituency 220", candidate: "Ma. Subramanian", party: "DMK", margin: 16025, rounds: 10, status: "Won", district: "Others" },
  { name: "Gobichettipalayam", candidate: "Senthil Balaji", party: "DMK", margin: 2053, rounds: 16, status: "Leading", district: "Erode" },
  { name: "Madurai North", candidate: "E.V. Velu", party: "DMK", margin: 4547, rounds: 16, status: "Leading", district: "Madurai" },
  { name: "Ariyalur", candidate: "Thangam Thennarasu", party: "DMK", margin: 8927, rounds: 15, status: "Leading", district: "Perambalur" },
  { name: "Kilvaithinankuppam", candidate: "K. Ponmudy", party: "DMK", margin: 14374, rounds: 15, status: "Won", district: "Vellore" },
  { name: "Thirumazhisai", candidate: "Anbil Mahesh Poyyamozhi", party: "DMK", margin: 6608, rounds: 10, status: "Won", district: "Kancheepuram" },
  { name: "Veppanahalli", candidate: "I. Periyasamy", party: "DMK", margin: 11620, rounds: 13, status: "Tight Fight", district: "Dharmapuri" },
  { name: "Kattumannarkoil", candidate: "R. Sakkarapani", party: "DMK", margin: 7764, rounds: 10, status: "Leading", district: "Cuddalore" },
  { name: "Nannilam", candidate: "M.R.K. Panneerselvam", party: "DMK", margin: 8262, rounds: 10, status: "Leading", district: "Thanjavur" },
  { name: "Nilakottai", candidate: "S.S. Sivasankar", party: "DMK", margin: 7110, rounds: 13, status: "Won", district: "Dindigul" },
  { name: "Constituency 222", candidate: "P. Moorthy", party: "DMK", margin: 6072, rounds: 12, status: "Leading", district: "Others" },
  { name: "Palani", candidate: "K. Selvaperunthagai", party: "DMK", margin: 11074, rounds: 14, status: "Leading", district: "Dindigul" },
  { name: "Papanasam", candidate: "M. Palanisamy", party: "DMK", margin: 11949, rounds: 16, status: "Won", district: "Thanjavur" },
  { name: "Royapuram", candidate: "R. Rajendran", party: "DMK", margin: 12896, rounds: 14, status: "Leading", district: "Chennai" },
  { name: "Kinathukadavu", candidate: "S. Regupathy", party: "DMK", margin: 16238, rounds: 11, status: "Won", district: "Coimbatore" },
  { name: "Anaikattu", candidate: "N. Kayalvizhi", party: "DMK", margin: 7725, rounds: 16, status: "Leading", district: "Vellore" },
  { name: "Kurinjipadi", candidate: "T. Mano Thangaraj", party: "DMK", margin: 16986, rounds: 14, status: "Tight Fight", district: "Cuddalore" },
  { name: "Gudalur", candidate: "C.V. Ganesan", party: "DMK", margin: 8431, rounds: 12, status: "Leading", district: "Nilgiris" },
  { name: "Thiru-Vi-Ka-Nagar", candidate: "S. Jayachitra", party: "DMK", margin: 3310, rounds: 10, status: "Leading", district: "Chennai" },
  { name: "Mannargudi", candidate: "K. Anbazhagan", party: "DMK", margin: 15303, rounds: 17, status: "Won", district: "Thanjavur" },
  { name: "Natham", candidate: "M. Subramanian", party: "DMK", margin: 3635, rounds: 16, status: "Leading", district: "Dindigul" },
  { name: "Sankarankovil", candidate: "M.K. Stalin", party: "DMK", margin: 15940, rounds: 10, status: "Leading", district: "Tirunelveli" },
  { name: "Vasudevanallur", candidate: "Udhayanidhi Stalin", party: "DMK", margin: 3160, rounds: 10, status: "Leading", district: "Tirunelveli" },
  { name: "Dindigul", candidate: "K.N. Nehru", party: "DMK", margin: 12568, rounds: 10, status: "Won", district: "Dindigul" },
  { name: "Constituency 224", candidate: "Duraimurugan", party: "DMK", margin: 9697, rounds: 14, status: "Won", district: "Others" },
  { name: "Vedasandur", candidate: "A. Raja", party: "DMK", margin: 13751, rounds: 11, status: "Won", district: "Dindigul" },
  { name: "Kalasapakkam", candidate: "T.R. Baalu", party: "DMK", margin: 14237, rounds: 15, status: "Leading", district: "Tiruvannamalai" },
  { name: "Orathanadu", candidate: "Kanimozhi", party: "DMK", margin: 9035, rounds: 12, status: "Won", district: "Thanjavur" },
  { name: "Jayankondam", candidate: "P.T.R. Palanivel Thiagarajan", party: "DMK", margin: 2278, rounds: 16, status: "Tight Fight", district: "Perambalur" },
  { name: "Constituency 226", candidate: "S. Muthusamy", party: "DMK", margin: 15446, rounds: 11, status: "Won", district: "Others" },
  { name: "Ambattur", candidate: "Ma. Subramanian", party: "DMK", margin: 13803, rounds: 17, status: "Won", district: "Chennai" },
  { name: "Vanur", candidate: "Senthil Balaji", party: "DMK", margin: 2965, rounds: 14, status: "Leading", district: "Villupuram" },
  { name: "Constituency 223", candidate: "E.V. Velu", party: "DMK", margin: 14423, rounds: 10, status: "Leading", district: "Others" },
  { name: "Bhuvanagiri", candidate: "Thangam Thennarasu", party: "DMK", margin: 14623, rounds: 12, status: "Tight Fight", district: "Cuddalore" },
  { name: "Constituency 229", candidate: "K. Ponmudy", party: "DMK", margin: 16215, rounds: 16, status: "Tight Fight", district: "Others" },
  { name: "Bargur", candidate: "Anbil Mahesh Poyyamozhi", party: "DMK", margin: 2460, rounds: 14, status: "Leading", district: "Dharmapuri" },
  { name: "Kavundampalayam", candidate: "I. Periyasamy", party: "DMK", margin: 4839, rounds: 11, status: "Leading", district: "Coimbatore" },
  { name: "Nanguneri", candidate: "R. Sakkarapani", party: "DMK", margin: 15691, rounds: 14, status: "Leading", district: "Tirunelveli" },
  { name: "Kallakurichi", candidate: "M.R.K. Panneerselvam", party: "DMK", margin: 14276, rounds: 17, status: "Won", district: "Villupuram" },
  { name: "Peravurani", candidate: "S.S. Sivasankar", party: "DMK", margin: 14777, rounds: 13, status: "Won", district: "Thanjavur" },
  { name: "Constituency 227", candidate: "P. Moorthy", party: "DMK", margin: 10187, rounds: 14, status: "Leading", district: "Others" },
  { name: "Chepauk-Thiruvallikeni", candidate: "K. Selvaperunthagai", party: "DMK", margin: 14883, rounds: 17, status: "Won", district: "Chennai" },
  { name: "Vellore", candidate: "M. Palanisamy", party: "DMK", margin: 14210, rounds: 15, status: "Leading", district: "Vellore" },
  { name: "Thanjavur", candidate: "R. Rajendran", party: "DMK", margin: 3546, rounds: 14, status: "Leading", district: "Thanjavur" },
  { name: "Mayiladuthurai", candidate: "S. Regupathy", party: "DMK", margin: 9696, rounds: 11, status: "Leading", district: "Thanjavur" },
  { name: "Sankarapuram", candidate: "N. Kayalvizhi", party: "DMK", margin: 6958, rounds: 13, status: "Won", district: "Villupuram" },
  { name: "Killiyoor", candidate: "T. Mano Thangaraj", party: "DMK", margin: 15403, rounds: 15, status: "Tight Fight", district: "Kanyakumari" },
  { name: "Alangudi", candidate: "C.V. Ganesan", party: "DMK", margin: 15887, rounds: 15, status: "Leading", district: "Pudukkottai" },
  { name: "Constituency 230", candidate: "S. Jayachitra", party: "DMK", margin: 13335, rounds: 11, status: "Tight Fight", district: "Others" },
  { name: "Perambur", candidate: "K. Anbazhagan", party: "DMK", margin: 11910, rounds: 10, status: "Tight Fight", district: "Chennai" },
  { name: "Madurai West", candidate: "M. Subramanian", party: "DMK", margin: 5674, rounds: 17, status: "Won", district: "Madurai" },
  { name: "Mylapore", candidate: "M.K. Stalin", party: "DMK", margin: 12627, rounds: 16, status: "Leading", district: "Chennai" },
  { name: "Pudukkottai", candidate: "Udhayanidhi Stalin", party: "DMK", margin: 14698, rounds: 17, status: "Won", district: "Pudukkottai" },
  { name: "Sholavandan", candidate: "K.N. Nehru", party: "DMK", margin: 9174, rounds: 13, status: "Tight Fight", district: "Madurai" },
  { name: "Nagapattinam", candidate: "Duraimurugan", party: "DMK", margin: 5491, rounds: 11, status: "Leading", district: "Thanjavur" },
  { name: "Villupuram", candidate: "A. Raja", party: "DMK", margin: 16739, rounds: 12, status: "Leading", district: "Villupuram" },
  { name: "Karaikudi", candidate: "T.R. Baalu", party: "DMK", margin: 11406, rounds: 14, status: "Tight Fight", district: "Pudukkottai" },
  { name: "Gudiyatham", candidate: "Kanimozhi", party: "DMK", margin: 12398, rounds: 11, status: "Leading", district: "Vellore" },
  { name: "Arani", candidate: "P.T.R. Palanivel Thiagarajan", party: "DMK", margin: 13737, rounds: 13, status: "Tight Fight", district: "Tiruvannamalai" },
  { name: "Gummidipoondi", candidate: "S. Muthusamy", party: "DMK", margin: 6173, rounds: 12, status: "Leading", district: "Chennai" },
  { name: "Kunnam", candidate: "Ma. Subramanian", party: "DMK", margin: 16440, rounds: 17, status: "Won", district: "Perambalur" },
  { name: "Srivaikuntam", candidate: "Senthil Balaji", party: "DMK", margin: 4619, rounds: 15, status: "Tight Fight", district: "Thoothukudi" },
  { name: "Karur", candidate: "E.V. Velu", party: "DMK", margin: 16797, rounds: 12, status: "Won", district: "Trichy" },
  { name: "Rasipuram", candidate: "Thangam Thennarasu", party: "DMK", margin: 5747, rounds: 14, status: "Won", district: "Namakkal" },
  { name: "Dr. Radhakrishnan Nagar", candidate: "K. Ponmudy", party: "DMK", margin: 6721, rounds: 14, status: "Leading", district: "Chennai" },
  { name: "Nagercoil", candidate: "Anbil Mahesh Poyyamozhi", party: "DMK", margin: 8911, rounds: 17, status: "Won", district: "Kanyakumari" },
  { name: "Thuraiyur", candidate: "I. Periyasamy", party: "DMK", margin: 14159, rounds: 17, status: "Won", district: "Trichy" },
  { name: "Trichy West", candidate: "R. Sakkarapani", party: "DMK", margin: 12536, rounds: 10, status: "Won", district: "Trichy" },
  { name: "Constituency 217", candidate: "M.R.K. Panneerselvam", party: "DMK", margin: 11959, rounds: 10, status: "Leading", district: "Others" },
  { name: "Jolarpet", candidate: "S.S. Sivasankar", party: "DMK", margin: 13631, rounds: 14, status: "Leading", district: "Vellore" },
  { name: "Kanyakumari", candidate: "P. Moorthy", party: "DMK", margin: 7942, rounds: 15, status: "Won", district: "Kanyakumari" },
  { name: "Padmanabhapuram", candidate: "K. Selvaperunthagai", party: "DMK", margin: 14252, rounds: 12, status: "Leading", district: "Kanyakumari" },
  { name: "Manachanallur", candidate: "M. Palanisamy", party: "DMK", margin: 16317, rounds: 17, status: "Won", district: "Trichy" },
  { name: "Thoothukudi", candidate: "R. Rajendran", party: "DMK", margin: 5465, rounds: 10, status: "Leading", district: "Thoothukudi" },
  { name: "T. Nagar", candidate: "S. Regupathy", party: "DMK", margin: 8622, rounds: 10, status: "Won", district: "Chennai" },
  { name: "Manapparai", candidate: "N. Kayalvizhi", party: "DMK", margin: 2646, rounds: 14, status: "Tight Fight", district: "Trichy" },
  { name: "Velachery", candidate: "T. Mano Thangaraj", party: "DMK", margin: 9813, rounds: 15, status: "Leading", district: "Chennai" },
  { name: "Ranipet", candidate: "C.V. Ganesan", party: "DMK", margin: 14093, rounds: 11, status: "Leading", district: "Kancheepuram" },
  { name: "Virudhunagar", candidate: "S. Jayachitra", party: "DMK", margin: 10491, rounds: 14, status: "Won", district: "Virudhunagar" },
  { name: "Erode East", candidate: "K. Anbazhagan", party: "DMK", margin: 2804, rounds: 12, status: "Leading", district: "Erode" },
  { name: "Villivakkam", candidate: "M. Subramanian", party: "DMK", margin: 7524, rounds: 14, status: "Won", district: "Chennai" },
  { name: "Hosur", candidate: "M.K. Stalin", party: "DMK", margin: 8085, rounds: 10, status: "Leading", district: "Dharmapuri" },
  { name: "Alandur", candidate: "Udhayanidhi Stalin", party: "DMK", margin: 7880, rounds: 12, status: "Leading", district: "Chennai" },
  { name: "Tambaram", candidate: "K.N. Nehru", party: "DMK", margin: 11766, rounds: 11, status: "Won", district: "Kancheepuram" },
  { name: "Tiruchuli", candidate: "Duraimurugan", party: "DMK", margin: 6017, rounds: 17, status: "Won", district: "Virudhunagar" },
  { name: "Krishnarayapuram", candidate: "A. Raja", party: "DMK", margin: 5060, rounds: 17, status: "Won", district: "Trichy" },
  { name: "Tenkasi", candidate: "M. Vijayakumar", party: "AIADMK", margin: 2176, rounds: 16, status: "Leading", district: "Tirunelveli" },
  { name: "Vilavancode", candidate: "Edappadi K. Palaniswami", party: "AIADMK", margin: 9562, rounds: 12, status: "Leading", district: "Kanyakumari" },
  { name: "Tiruvadanai", candidate: "O. Panneerselvam", party: "AIADMK", margin: 11964, rounds: 14, status: "Leading", district: "Ramanathapuram" },
  { name: "Perundurai", candidate: "C.Ve. Shanmugam", party: "AIADMK", margin: 6438, rounds: 15, status: "Tight Fight", district: "Erode" },
  { name: "Ottapidaram", candidate: "P. Thangamani", party: "AIADMK", margin: 4063, rounds: 14, status: "Leading", district: "Thoothukudi" },
  { name: "Palladam", candidate: "S.P. Velumani", party: "AIADMK", margin: 13427, rounds: 11, status: "Tight Fight", district: "Coimbatore" },
  { name: "Tiruvannamalai", candidate: "D. Jayakumar", party: "AIADMK", margin: 12428, rounds: 14, status: "Tight Fight", district: "Tiruvannamalai" },
  { name: "Valparai", candidate: "K.P. Munusamy", party: "AIADMK", margin: 12306, rounds: 14, status: "Tight Fight", district: "Coimbatore" },
  { name: "Kancheepuram", candidate: "R.B. Udayakumar", party: "AIADMK", margin: 12177, rounds: 12, status: "Leading", district: "Kancheepuram" },
  { name: "Andipatti", candidate: "C. Vijayabaskar", party: "AIADMK", margin: 3522, rounds: 15, status: "Leading", district: "Madurai" },
  { name: "Kolathur", candidate: "M.R. Vijayabhaskar", party: "AIADMK", margin: 4091, rounds: 16, status: "Leading", district: "Chennai" },
  { name: "Salem South", candidate: "Vaithilingam", party: "AIADMK", margin: 12012, rounds: 14, status: "Leading", district: "Salem" },
  { name: "Modakurichi", candidate: "P. Benjamin", party: "AIADMK", margin: 5574, rounds: 17, status: "Won", district: "Erode" },
  { name: "Constituency 231", candidate: "P. Saravanan", party: "AIADMK", margin: 9865, rounds: 10, status: "Won", district: "Others" },
  { name: "Kulithalai", candidate: "K.T. Rajenthra Bhalaji", party: "AIADMK", margin: 7982, rounds: 16, status: "Tight Fight", district: "Trichy" },
  { name: "Ponneri", candidate: "A. Anwar Raajhaa", party: "AIADMK", margin: 2247, rounds: 11, status: "Won", district: "Chennai" },
  { name: "Vedaranyam", candidate: "M.K. Vishnu", party: "AIADMK", margin: 12245, rounds: 16, status: "Won", district: "Thanjavur" },
  { name: "Tiruchendur", candidate: "S. Semmalai", party: "AIADMK", margin: 8020, rounds: 16, status: "Leading", district: "Thoothukudi" },
  { name: "Tiruttani", candidate: "K. Pandiarajan", party: "AIADMK", margin: 7580, rounds: 13, status: "Tight Fight", district: "Chennai" },
  { name: "Cheyyur", candidate: "Natham R. Viswanathan", party: "AIADMK", margin: 12202, rounds: 12, status: "Leading", district: "Kancheepuram" },
  { name: "R.K. Nagar", candidate: "V.V. Rajan Chellappa", party: "AIADMK", margin: 3885, rounds: 11, status: "Won", district: "Chennai" },
  { name: "Paramakudi", candidate: "R. Vaithilingam", party: "AIADMK", margin: 11830, rounds: 13, status: "Tight Fight", district: "Ramanathapuram" },
  { name: "Thiruvaiyaru", candidate: "S. Ganesh", party: "AIADMK", margin: 11570, rounds: 13, status: "Leading", district: "Thanjavur" },
  { name: "Udhagamandalam", candidate: "K. Raju", party: "AIADMK", margin: 4517, rounds: 14, status: "Tight Fight", district: "Nilgiris" },
  { name: "Vaniyambadi", candidate: "M. Vijayakumar", party: "AIADMK", margin: 8039, rounds: 14, status: "Won", district: "Vellore" },
  { name: "Madambakkam", candidate: "Edappadi K. Palaniswami", party: "AIADMK", margin: 6640, rounds: 16, status: "Won", district: "Kancheepuram" },
  { name: "Theni", candidate: "O. Panneerselvam", party: "AIADMK", margin: 2790, rounds: 14, status: "Won", district: "Theni" },
  { name: "Cuddalore", candidate: "C.Ve. Shanmugam", party: "AIADMK", margin: 10534, rounds: 10, status: "Leading", district: "Cuddalore" },
  { name: "Thiruvallur", candidate: "P. Thangamani", party: "AIADMK", margin: 6131, rounds: 14, status: "Tight Fight", district: "Chennai" },
  { name: "Rajapalayam", candidate: "S.P. Velumani", party: "AIADMK", margin: 12129, rounds: 14, status: "Won", district: "Virudhunagar" },
  { name: "Aravakurichi", candidate: "D. Jayakumar", party: "AIADMK", margin: 7205, rounds: 14, status: "Won", district: "Trichy" },
  { name: "Tirupattur", candidate: "K.P. Munusamy", party: "AIADMK", margin: 12966, rounds: 12, status: "Leading", district: "Vellore" },
  { name: "Ramanathapuram", candidate: "R.B. Udayakumar", party: "AIADMK", margin: 3267, rounds: 15, status: "Won", district: "Ramanathapuram" },
  { name: "Krishnagiri", candidate: "C. Vijayabaskar", party: "AIADMK", margin: 5877, rounds: 13, status: "Won", district: "Dharmapuri" },
  { name: "Palacode", candidate: "M.R. Vijayabhaskar", party: "AIADMK", margin: 2262, rounds: 13, status: "Won", district: "Dharmapuri" },
  { name: "Salem West", candidate: "Vaithilingam", party: "AIADMK", margin: 12515, rounds: 14, status: "Leading", district: "Salem" },
  { name: "Constituency 232", candidate: "P. Benjamin", party: "AIADMK", margin: 10393, rounds: 12, status: "Tight Fight", district: "Others" },
  { name: "Madurai South", candidate: "P. Saravanan", party: "AIADMK", margin: 6387, rounds: 10, status: "Tight Fight", district: "Madurai" },
  { name: "Saidapet", candidate: "K.T. Rajenthra Bhalaji", party: "AIADMK", margin: 5194, rounds: 15, status: "Tight Fight", district: "Chennai" },
  { name: "Madurantakam", candidate: "A. Anwar Raajhaa", party: "AIADMK", margin: 13182, rounds: 14, status: "Tight Fight", district: "Kancheepuram" },
  { name: "Periyakulam", candidate: "M.K. Vishnu", party: "AIADMK", margin: 7419, rounds: 10, status: "Tight Fight", district: "Theni" },
  { name: "Yercaud", candidate: "S. Semmalai", party: "AIADMK", margin: 4098, rounds: 13, status: "Tight Fight", district: "Salem" },
  { name: "Uthiramerur", candidate: "K. Pandiarajan", party: "AIADMK", margin: 6649, rounds: 12, status: "Won", district: "Kancheepuram" },
  { name: "Cumbum", candidate: "Natham R. Viswanathan", party: "AIADMK", margin: 9695, rounds: 10, status: "Won", district: "Theni" },
  { name: "Lalgudi", candidate: "V.V. Rajan Chellappa", party: "AIADMK", margin: 2976, rounds: 16, status: "Won", district: "Trichy" },
  { name: "Namakkal", candidate: "R. Vaithilingam", party: "AIADMK", margin: 12607, rounds: 17, status: "Won", district: "Namakkal" },
  { name: "Constituency 218", candidate: "S. Ganesh", party: "AIADMK", margin: 13149, rounds: 16, status: "Leading", district: "Others" },
  { name: "Dharmapuri", candidate: "K. Raju", party: "AIADMK", margin: 11432, rounds: 16, status: "Leading", district: "Dharmapuri" },
  { name: "Bhavanisagar", candidate: "M. Vijayakumar", party: "AIADMK", margin: 3485, rounds: 13, status: "Won", district: "Coimbatore" },
  { name: "Sivakasi", candidate: "Edappadi K. Palaniswami", party: "AIADMK", margin: 9341, rounds: 15, status: "Tight Fight", district: "Virudhunagar" },
  { name: "Veerapandi", candidate: "O. Panneerselvam", party: "AIADMK", margin: 7659, rounds: 15, status: "Won", district: "Salem" },
  { name: "Pattukkottai", candidate: "C.Ve. Shanmugam", party: "AIADMK", margin: 5101, rounds: 12, status: "Leading", district: "Thanjavur" },
  { name: "Coimbatore South", candidate: "P. Thangamani", party: "AIADMK", margin: 3452, rounds: 15, status: "Won", district: "Coimbatore" },
  { name: "Anna Nagar", candidate: "S.P. Velumani", party: "AIADMK", margin: 10550, rounds: 17, status: "Won", district: "Chennai" },
  { name: "Anthiyur", candidate: "D. Jayakumar", party: "AIADMK", margin: 7303, rounds: 12, status: "Leading", district: "Erode" },
  { name: "Ambasamudram", candidate: "K.P. Munusamy", party: "AIADMK", margin: 13446, rounds: 17, status: "Won", district: "Tirunelveli" },
  { name: "Sirkazhi", candidate: "R.B. Udayakumar", party: "AIADMK", margin: 12767, rounds: 12, status: "Leading", district: "Cuddalore" },
  { name: "Kilpennathur", candidate: "C. Vijayabaskar", party: "AIADMK", margin: 10968, rounds: 10, status: "Leading", district: "Tiruvannamalai" },
  { name: "Trichy East", candidate: "M.R. Vijayabhaskar", party: "AIADMK", margin: 8568, rounds: 17, status: "Won", district: "Trichy" },
  { name: "Salem North", candidate: "Vaithilingam", party: "AIADMK", margin: 6206, rounds: 14, status: "Won", district: "Salem" },
  { name: "Thiruparankundram", candidate: "P. Benjamin", party: "AIADMK", margin: 8636, rounds: 17, status: "Won", district: "Madurai" },
  { name: "Thiruverumbur", candidate: "P. Saravanan", party: "AIADMK", margin: 7382, rounds: 11, status: "Leading", district: "Trichy" },
  { name: "Singanallur", candidate: "K.T. Rajenthra Bhalaji", party: "AIADMK", margin: 6870, rounds: 10, status: "Leading", district: "Coimbatore" },
  { name: "Melur", candidate: "A. Anwar Raajhaa", party: "AIADMK", margin: 7517, rounds: 11, status: "Leading", district: "Madurai" },
  { name: "Avadi", candidate: "M.K. Vishnu", party: "AIADMK", margin: 13003, rounds: 10, status: "Won", district: "Chennai" },
  { name: "Sulur", candidate: "L. Murugan", party: "TVK", margin: 7548, rounds: 17, status: "Won", district: "Coimbatore" },
  { name: "Chidambaram", candidate: "P. Anand", party: "TVK", margin: 3783, rounds: 16, status: "Leading", district: "Cuddalore" },
  { name: "Maduravoyal", candidate: "R. Karthikeyan", party: "TVK", margin: 7604, rounds: 14, status: "Tight Fight", district: "Chennai" },
  { name: "Virugambakkam", candidate: "S. Priya", party: "TVK", margin: 5764, rounds: 16, status: "Leading", district: "Chennai" },
  { name: "Arakkonam", candidate: "V. Ramesh", party: "TVK", margin: 3923, rounds: 14, status: "Won", district: "Kancheepuram" },
  { name: "Aruppukottai", candidate: "Vijay", party: "TVK", margin: 1481, rounds: 17, status: "Won", district: "Virudhunagar" },
  { name: "Mudhukulathur", candidate: "A. Rajan", party: "TVK", margin: 6980, rounds: 16, status: "Won", district: "Ramanathapuram" },
  { name: "Madurai East", candidate: "S. Durai", party: "TVK", margin: 1121, rounds: 14, status: "Tight Fight", district: "Madurai" },
  { name: "Rishivandiyam", candidate: "K. Mohan", party: "TVK", margin: 5891, rounds: 16, status: "Won", district: "Villupuram" },
  { name: "Musiri", candidate: "P. Manikandan", party: "TVK", margin: 4923, rounds: 10, status: "Leading", district: "Trichy" },
  { name: "Coonoor", candidate: "R. Selvam", party: "TVK", margin: 6435, rounds: 13, status: "Leading", district: "Nilgiris" },
  { name: "Kilvelur", candidate: "T. Venkatesan", party: "TVK", margin: 6068, rounds: 12, status: "Tight Fight", district: "Thanjavur" },
  { name: "Thiruvottiyur", candidate: "M. Arun Kumar", party: "TVK", margin: 8397, rounds: 17, status: "Won", district: "Chennai" },
  { name: "Harur", candidate: "S. Bharathi", party: "TVK", margin: 4452, rounds: 12, status: "Won", district: "Salem" },
  { name: "Uthangarai", candidate: "K. Saravanan", party: "TVK", margin: 3302, rounds: 15, status: "Leading", district: "Dharmapuri" },
  { name: "Tiruppur South", candidate: "L. Murugan", party: "TVK", margin: 896, rounds: 12, status: "Won", district: "Coimbatore" },
  { name: "Thiruvidaimarudur", candidate: "P. Anand", party: "TVK", margin: 1753, rounds: 17, status: "Won", district: "Thanjavur" },
  { name: "Poonamallee", candidate: "R. Karthikeyan", party: "TVK", margin: 5912, rounds: 13, status: "Leading", district: "Chennai" },
  { name: "Vandavasi", candidate: "S. Priya", party: "TVK", margin: 8146, rounds: 12, status: "Leading", district: "Tiruvannamalai" },
  { name: "Vikravandi", candidate: "V. Ramesh", party: "TVK", margin: 2710, rounds: 16, status: "Leading", district: "Villupuram" },
  { name: "Radhapuram", candidate: "Vijay", party: "TVK", margin: 1251, rounds: 16, status: "Won", district: "Tirunelveli" },
  { name: "Tirunelveli", candidate: "A. Rajan", party: "TVK", margin: 8452, rounds: 14, status: "Leading", district: "Tirunelveli" },
  { name: "Constituency 233", candidate: "S. Durai", party: "TVK", margin: 4884, rounds: 13, status: "Tight Fight", district: "Others" },
  { name: "Polur", candidate: "K. Mohan", party: "TVK", margin: 5277, rounds: 12, status: "Leading", district: "Tiruvannamalai" },
  { name: "Sriperumbudur", candidate: "P. Manikandan", party: "TVK", margin: 1984, rounds: 17, status: "Won", district: "Kancheepuram" },
  { name: "Bodinayakanur", candidate: "R. Selvam", party: "TVK", margin: 3884, rounds: 13, status: "Leading", district: "Theni" },
  { name: "Aranthangi", candidate: "T. Venkatesan", party: "TVK", margin: 1915, rounds: 12, status: "Won", district: "Pudukkottai" },
  { name: "Palayamkottai", candidate: "M. Arun Kumar", party: "TVK", margin: 2593, rounds: 16, status: "Tight Fight", district: "Tirunelveli" },
  { name: "Pennagaram", candidate: "S. Bharathi", party: "TVK", margin: 6079, rounds: 13, status: "Leading", district: "Dharmapuri" },
  { name: "Mettur", candidate: "K. Saravanan", party: "TVK", margin: 6665, rounds: 15, status: "Won", district: "Salem" },
  { name: "Arcot", candidate: "L. Murugan", party: "TVK", margin: 1712, rounds: 15, status: "Leading", district: "Kancheepuram" },
  { name: "Constituency 234", candidate: "P. Anand", party: "TVK", margin: 8448, rounds: 16, status: "Tight Fight", district: "Others" },
  { name: "Gingee", candidate: "R. Karthikeyan", party: "TVK", margin: 3665, rounds: 15, status: "Leading", district: "Villupuram" },
  { name: "Constituency 216", candidate: "S. Priya", party: "TVK", margin: 8057, rounds: 17, status: "Won", district: "Others" },
  { name: "Madhavaram", candidate: "V. Ramesh", party: "TVK", margin: 3178, rounds: 15, status: "Leading", district: "Chennai" },
  { name: "Tiruppur North", candidate: "Vijay", party: "TVK", margin: 1401, rounds: 10, status: "Leading", district: "Coimbatore" },
  { name: "Sivagangai", candidate: "A. Rajan", party: "TVK", margin: 3702, rounds: 17, status: "Won", district: "Pudukkottai" },
  { name: "Sholinganallur", candidate: "S. Durai", party: "TVK", margin: 4235, rounds: 16, status: "Tight Fight", district: "Chennai" },
  { name: "Sankari", candidate: "K. Mohan", party: "TVK", margin: 8684, rounds: 17, status: "Won", district: "Salem" },
  { name: "Madurai Central", candidate: "P. Manikandan", party: "TVK", margin: 4556, rounds: 17, status: "Won", district: "Madurai" },
  { name: "Coimbatore North", candidate: "Tamilisai Soundararajan", party: "BJP", margin: 3363, rounds: 16, status: "Won", district: "Coimbatore" },
  { name: "Tindivanam", candidate: "C.P. Radhakrishnan", party: "BJP", margin: 2127, rounds: 17, status: "Won", district: "Villupuram" },
  { name: "Harbour", candidate: "S. Narayanan", party: "BJP", margin: 2590, rounds: 14, status: "Leading", district: "Chennai" },
  { name: "Constituency 219", candidate: "K. Shanmugam", party: "BJP", margin: 4334, rounds: 16, status: "Won", district: "Others" },
  { name: "Mangadu", candidate: "P. Selvam", party: "BJP", margin: 5244, rounds: 15, status: "Leading", district: "Kancheepuram" },
  { name: "Tiruchengode", candidate: "R. Mohan", party: "BJP", margin: 587, rounds: 17, status: "Won", district: "Namakkal" },
  { name: "Ulundurpettai", candidate: "V. Prakash", party: "BJP", margin: 2839, rounds: 12, status: "Won", district: "Villupuram" },
  { name: "Pappireddipatti", candidate: "M. Raghu", party: "BJP", margin: 5407, rounds: 11, status: "Leading", district: "Salem" },
  { name: "Perambalur", candidate: "S. Kumar", party: "BJP", margin: 2005, rounds: 11, status: "Won", district: "Perambalur" },
  { name: "Erode West", candidate: "T. Anand", party: "BJP", margin: 3541, rounds: 12, status: "Tight Fight", district: "Erode" },
  { name: "Constituency 215", candidate: "K. Annamalai", party: "BJP", margin: 2967, rounds: 17, status: "Won", district: "Others" },
  { name: "Egmore", candidate: "Vanathi Srinivasan", party: "BJP", margin: 5154, rounds: 17, status: "Won", district: "Chennai" },
  { name: "Constituency 225", candidate: "Nainar Nagendran", party: "BJP", margin: 973, rounds: 14, status: "Won", district: "Others" },
  { name: "Omalur", candidate: "L. Murugan", party: "BJP", margin: 1005, rounds: 13, status: "Won", district: "Salem" },
  { name: "Colachel", candidate: "H. Raja", party: "BJP", margin: 4851, rounds: 10, status: "Won", district: "Kanyakumari" },
  { name: "Usilampatti", candidate: "M. Kumaresan", party: "NTK", margin: 907, rounds: 15, status: "Leading", district: "Madurai" },
  { name: "Pollachi", candidate: "T. Poongodi", party: "NTK", margin: 2213, rounds: 13, status: "Won", district: "Coimbatore" },
  { name: "Srivilliputhur", candidate: "R. Chelladurai", party: "NTK", margin: 3983, rounds: 12, status: "Won", district: "Virudhunagar" },
  { name: "Oddanchatram", candidate: "V. Sundaram", party: "NTK", margin: 3953, rounds: 13, status: "Leading", district: "Dindigul" },
  { name: "Chengalpattu", candidate: "P. Arumugam", party: "NTK", margin: 1078, rounds: 16, status: "Leading", district: "Kancheepuram" },
  { name: "Edappadi", candidate: "Seeman", party: "NTK", margin: 434, rounds: 14, status: "Tight Fight", district: "Salem" },
  { name: "Sattur", candidate: "P. Karthikeyan", party: "NTK", margin: 2642, rounds: 15, status: "Leading", district: "Virudhunagar" },
  { name: "Constituency 228", candidate: "R. Velu", party: "NTK", margin: 1876, rounds: 10, status: "Leading", district: "Others" },
  { name: "Paramathi-Velur", candidate: "S. Anbalagan", party: "NTK", margin: 1375, rounds: 16, status: "Leading", district: "Namakkal" },
  { name: "Bhavani", candidate: "K. Dhanasekaran", party: "NTK", margin: 2327, rounds: 10, status: "Won", district: "Erode" },
  { name: "Thirumayam", candidate: "D. Ravikumar", party: "Others", margin: 695, rounds: 12, status: "Leading", district: "Pudukkottai" },
  { name: "Pallavaram", candidate: "Thol. Thirumavalavan", party: "Others", margin: 3722, rounds: 13, status: "Leading", district: "Kancheepuram" },
  { name: "Kovilpatti", candidate: "G.K. Vasan", party: "Others", margin: 2372, rounds: 12, status: "Leading", district: "Thoothukudi" },
  { name: "Thirumangalam", candidate: "S. Ramadoss", party: "Others", margin: 3214, rounds: 12, status: "Won", district: "Virudhunagar" },
  { name: "Cheyyar", candidate: "Anbumani Ramadoss", party: "Others", margin: 2752, rounds: 15, status: "Leading", district: "Tiruvannamalai" },
  { name: "Constituency 221", candidate: "T. Velmurugan", party: "Others", margin: 2062, rounds: 16, status: "Tight Fight", district: "Others" },
  { name: "Thiruporur", candidate: "Vaiko", party: "Others", margin: 4018, rounds: 14, status: "Tight Fight", district: "Kancheepuram" },
  { name: "Kumarapalayam", candidate: "M. Kalaignar", party: "Others", margin: 956, rounds: 10, status: "Leading", district: "Namakkal" },
  { name: "Vilathikulam", candidate: "P. Ramasamy", party: "Others", margin: 352, rounds: 11, status: "Leading", district: "Thoothukudi" },
];
