export const ELECTION_YEARS = [2021, 2016, 2011, 2006, 2001, 1996, 1991, 1989, 1984, 1980, 1977, 1971, 1967, 1962, 1957, 1952];

export const HISTORICAL_RESULTS = {
  2021: {
    totalSeats: 234, turnout: '72.78%', chiefMinister: 'M.K. Stalin', rulingParty: 'DMK',
    parties: [
      { party: 'DMK+', seats: 159, voteShare: 37.7, status: 'Won', change: '+70' },
      { party: 'AIADMK+', seats: 75, voteShare: 33.29, status: 'Lost', change: '-61' },
      { party: 'MNM', seats: 0, voteShare: 2.39, status: 'Lost', change: '0' },
      { party: 'NTK', seats: 0, voteShare: 6.58, status: 'Lost', change: '0' },
      { party: 'BJP', seats: 4, voteShare: 2.65, status: '-', change: '+4' },
      { party: 'Others', seats: 0, voteShare: 17.39, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Kolathur', winner: 'M.K. Stalin', party: 'DMK', margin: 92737 },
      { name: 'Edappadi', winner: 'Edappadi K. Palaniswami', party: 'AIADMK', margin: 67738 },
      { name: 'Chepauk-Thiruvallikeni', winner: 'Udhayanidhi Stalin', party: 'DMK', margin: 74020 },
      { name: 'Coimbatore South', winner: 'Vanathi Srinivasan', party: 'BJP', margin: 1540 },
      { name: 'Thousand Lights', winner: 'Dr. Ezhilan Naganathan', party: 'DMK', margin: 40753 },
      { name: 'Madurai Central', winner: 'PTR Palanivel Thiagarajan', party: 'DMK', margin: 54095 },
    ],
    highlights: [
      'DMK alliance swept to power after 10 years in opposition',
      'M.K. Stalin became Chief Minister for the first time',
      'AIADMK contested without Jayalalithaa for first time',
      'BJP won 4 seats — its best-ever performance in TN',
      'NTK and MNM failed to win any seats despite high vote share',
    ],
  },
  2016: {
    totalSeats: 234, turnout: '74.26%', chiefMinister: 'J. Jayalalithaa', rulingParty: 'AIADMK',
    parties: [
      { party: 'AIADMK', seats: 136, voteShare: 40.77, status: 'Won', change: '-14' },
      { party: 'DMK+', seats: 89, voteShare: 31.64, status: 'Lost', change: '+66' },
      { party: 'PMK', seats: 0, voteShare: 5.32, status: 'Lost', change: '-3' },
      { party: 'BJP', seats: 0, voteShare: 2.84, status: 'Lost', change: '0' },
      { party: 'DMDK', seats: 0, voteShare: 2.39, status: 'Lost', change: '-23' },
      { party: 'Others', seats: 9, voteShare: 17.04, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'RK Nagar', winner: 'J. Jayalalithaa', party: 'AIADMK', margin: 70956 },
      { name: 'Kolathur', winner: 'M.K. Stalin', party: 'DMK', margin: 37279 },
      { name: 'Thiruvarur', winner: 'M. Karunanidhi', party: 'DMK', margin: 73209 },
      { name: 'Edappadi', winner: 'Edappadi K. Palaniswami', party: 'AIADMK', margin: 46478 },
      { name: 'Modakurichi', winner: 'O. Panneerselvam', party: 'AIADMK', margin: 56498 },
    ],
    highlights: [
      'AIADMK became first party in 32 years to win consecutive terms in TN',
      'Jayalalithaa led AIADMK to victory but passed away in Dec 2016',
      'DMK improved significantly from 2011 debacle',
      'DMDK lost all 23 seats it held previously',
      'PMK and BJP failed to win any seats',
    ],
  },
  2011: {
    totalSeats: 234, turnout: '78.44%', chiefMinister: 'J. Jayalalithaa', rulingParty: 'AIADMK',
    parties: [
      { party: 'AIADMK+', seats: 150, voteShare: 38.4, status: 'Won', change: '+54' },
      { party: 'DMK+', seats: 23, voteShare: 22.4, status: 'Lost', change: '-136' },
      { party: 'DMDK', seats: 29, voteShare: 7.8, status: '-', change: '+29' },
      { party: 'CPI(M)', seats: 10, voteShare: 2.07, status: '-', change: '+10' },
      { party: 'PMK', seats: 3, voteShare: 5.72, status: '-', change: '+3' },
      { party: 'Others', seats: 19, voteShare: 23.61, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'RK Nagar', winner: 'J. Jayalalithaa', party: 'AIADMK', margin: 49552 },
      { name: 'Kolathur', winner: 'M.K. Stalin', party: 'DMK', margin: 44523 },
      { name: 'Thirumangalam', winner: 'M. Karunanidhi', party: 'DMK', margin: 19984 },
      { name: 'Radhapuram', winner: 'P. Thangamani', party: 'AIADMK', margin: 16889 },
    ],
    highlights: [
      'AIADMK won massive landslide — biggest win in decades',
      'DMK suffered worst-ever defeat winning only 23 seats',
      'Anti-incumbency wave against DMK due to 2G scam',
      'DMDK emerged as third force with 29 seats',
      'Highest voter turnout in TN history at 78.44%',
    ],
  },
  2006: {
    totalSeats: 234, turnout: '73.65%', chiefMinister: 'M. Karunanidhi', rulingParty: 'DMK',
    parties: [
      { party: 'DMK+', seats: 163, voteShare: 46.25, status: 'Won', change: '+31' },
      { party: 'AIADMK+', seats: 61, voteShare: 38.19, status: 'Lost', change: '-133' },
      { party: 'PMK', seats: 18, voteShare: 5.87, status: '-', change: '+18' },
      { party: 'CPI', seats: 6, voteShare: 1.66, status: '-', change: '+6' },
      { party: 'Others', seats: 10, voteShare: 8.03, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Chepauk', winner: 'M. Karunanidhi', party: 'DMK', margin: 39000 },
      { name: 'Andipatti', winner: 'J. Jayalalithaa', party: 'AIADMK', margin: 15678 },
    ],
    highlights: [
      'DMK alliance won emphatic victory with 163 seats',
      'Karunanidhi became CM for the 5th time at age 82',
      'Anti-incumbency against Jayalalithaa government',
      'PMK allied with DMK and won 18 seats',
    ],
  },
  2001: {
    totalSeats: 234, turnout: '68.64%', chiefMinister: 'J. Jayalalithaa', rulingParty: 'AIADMK',
    parties: [
      { party: 'AIADMK+', seats: 194, voteShare: 48.16, status: 'Won', change: '+96' },
      { party: 'DMK+', seats: 31, voteShare: 30.93, status: 'Lost', change: '-126' },
      { party: 'PMK', seats: 20, voteShare: 5.87, status: '-', change: '+15' },
      { party: 'MDMK', seats: 4, voteShare: 3.05, status: '-', change: '+4' },
      { party: 'Others', seats: 9, voteShare: 11.99, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Andipatti', winner: 'J. Jayalalithaa', party: 'AIADMK', margin: 49221 },
      { name: 'Chepauk', winner: 'M. Karunanidhi', party: 'DMK', margin: 15000 },
    ],
    highlights: [
      'AIADMK won record 194 seats — biggest TN mandate ever',
      'DMK reduced to just 31 seats',
      'Jayalalithaa returned as CM despite pending cases',
      'Strong anti-DMK wave after corruption allegations',
    ],
  },
  1996: {
    totalSeats: 234, turnout: '73.65%', chiefMinister: 'M. Karunanidhi', rulingParty: 'DMK',
    parties: [
      { party: 'DMK+', seats: 219, voteShare: 52.31, status: 'Won', change: '+162' },
      { party: 'AIADMK+', seats: 4, voteShare: 21.48, status: 'Lost', change: '-160' },
      { party: 'TMC', seats: 20, voteShare: 7.1, status: '-', change: '+20' },
      { party: 'Others', seats: 11, voteShare: 19.11, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Chepauk', winner: 'M. Karunanidhi', party: 'DMK', margin: 42500 },
    ],
    highlights: [
      'DMK alliance won record 219 of 234 seats',
      'AIADMK won only 4 seats — worst defeat in its history',
      'Massive anti-AIADMK wave due to corruption and TANSI land deal',
      'TMC (G.K. Moopanar) emerged as a significant force',
    ],
  },
  1991: {
    totalSeats: 234, turnout: '71.62%', chiefMinister: 'J. Jayalalithaa', rulingParty: 'AIADMK',
    parties: [
      { party: 'AIADMK+', seats: 164, voteShare: 43.49, status: 'Won', change: '+37' },
      { party: 'DMK+', seats: 57, voteShare: 32.53, status: 'Lost', change: '-43' },
      { party: 'Congress', seats: 26, voteShare: 15.1, status: '-', change: '+26' },
      { party: 'Others', seats: 13, voteShare: 8.88, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Bargur', winner: 'J. Jayalalithaa', party: 'AIADMK', margin: 35600 },
    ],
    highlights: [
      'Jayalalithaa became CM for the first time at age 43',
      'AIADMK benefited from sympathy wave after MGR\'s death legacy',
      'Congress allied with AIADMK and won 26 seats',
      'Rajiv Gandhi assassination affected election dynamics',
    ],
  },
  1989: {
    totalSeats: 234, turnout: '63.60%', chiefMinister: 'M. Karunanidhi', rulingParty: 'DMK',
    parties: [
      { party: 'DMK+', seats: 150, voteShare: 45.09, status: 'Won', change: '+117' },
      { party: 'AIADMK+', seats: 27, voteShare: 30.35, status: 'Lost', change: '-105' },
      { party: 'Congress', seats: 26, voteShare: 12.8, status: '-', change: '+26' },
      { party: 'Janata Dal', seats: 2, voteShare: 3.2, status: '-', change: '+2' },
      { party: 'Others', seats: 29, voteShare: 8.56, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Chepauk', winner: 'M. Karunanidhi', party: 'DMK', margin: 48500 },
      { name: 'Thousand Lights', winner: 'J. Jayalalithaa', party: 'AIADMK', margin: 22100 },
    ],
    highlights: [
      'DMK returned to power after 13 years in opposition',
      'Karunanidhi became CM for the 4th time',
      'AIADMK suffered badly after MGR\'s death and party split',
      'Congress allied with DMK and won 26 seats',
      'Anti-incumbency and AIADMK internal feud led to defeat',
    ],
  },
  1984: {
    totalSeats: 234, turnout: '72.60%', chiefMinister: 'M.G. Ramachandran', rulingParty: 'AIADMK',
    parties: [
      { party: 'AIADMK+', seats: 132, voteShare: 42.55, status: 'Won', change: '-1' },
      { party: 'DMK+', seats: 98, voteShare: 39.87, status: 'Lost', change: '+60' },
      { party: 'Congress', seats: 0, voteShare: 6.12, status: 'Lost', change: '-15' },
      { party: 'Others', seats: 4, voteShare: 11.46, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Andipatti', winner: 'M.G. Ramachandran', party: 'AIADMK', margin: 41200 },
      { name: 'Chepauk', winner: 'M. Karunanidhi', party: 'DMK', margin: 29800 },
    ],
    highlights: [
      'MGR won his third consecutive term despite ill health',
      'MGR campaigned from hospital bed — massive sympathy wave',
      'DMK improved significantly gaining 60 seats',
      'Indira Gandhi assassination sympathy did not help Congress in TN',
      'This was MGR\'s last election — he passed away in 1987',
    ],
  },
  1980: {
    totalSeats: 234, turnout: '62.03%', chiefMinister: 'M.G. Ramachandran', rulingParty: 'AIADMK',
    parties: [
      { party: 'AIADMK+', seats: 133, voteShare: 38.96, status: 'Won', change: '-7' },
      { party: 'DMK+', seats: 38, voteShare: 22.14, status: 'Lost', change: '-15' },
      { party: 'Congress(I)', seats: 31, voteShare: 18.75, status: '-', change: '+25' },
      { party: 'Congress(U)', seats: 6, voteShare: 5.2, status: '-', change: '-16' },
      { party: 'Janata', seats: 2, voteShare: 3.82, status: '-', change: '-3' },
      { party: 'Others', seats: 24, voteShare: 11.13, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Andipatti', winner: 'M.G. Ramachandran', party: 'AIADMK', margin: 38900 },
      { name: 'Guindy', winner: 'M. Karunanidhi', party: 'DMK', margin: 18500 },
    ],
    highlights: [
      'MGR retained power with comfortable majority',
      'MGR\'s popularity and welfare schemes kept AIADMK dominant',
      'Congress split into Congress(I) under Indira and Congress(U)',
      'DMK performance declined significantly',
      'Emergency period aftermath still influenced political alignments',
    ],
  },
  1977: {
    totalSeats: 234, turnout: '65.78%', chiefMinister: 'M.G. Ramachandran', rulingParty: 'AIADMK',
    parties: [
      { party: 'AIADMK+', seats: 140, voteShare: 35.31, status: 'Won', change: '+140' },
      { party: 'DMK+', seats: 53, voteShare: 28.44, status: 'Lost', change: '-131' },
      { party: 'Congress', seats: 22, voteShare: 16.58, status: '-', change: '-27' },
      { party: 'Janata', seats: 5, voteShare: 6.92, status: '-', change: '+5' },
      { party: 'Others', seats: 14, voteShare: 12.75, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Andipatti', winner: 'M.G. Ramachandran', party: 'AIADMK', margin: 44000 },
      { name: 'Chepauk', winner: 'M. Karunanidhi', party: 'DMK', margin: 21300 },
    ],
    highlights: [
      'MGR founded AIADMK in 1972 and became CM on first attempt',
      'AIADMK won landslide in its first ever assembly election',
      'Emergency backlash weakened Congress and DMK alliance',
      'MGR\'s film star charisma drove massive popular support',
      'Beginning of the AIADMK era in Tamil Nadu politics',
    ],
  },
  1971: {
    totalSeats: 234, turnout: '76.60%', chiefMinister: 'M. Karunanidhi', rulingParty: 'DMK',
    parties: [
      { party: 'DMK+', seats: 184, voteShare: 48.58, status: 'Won', change: '+46' },
      { party: 'Congress', seats: 49, voteShare: 33.59, status: 'Lost', change: '-31' },
      { party: 'Swatantra', seats: 1, voteShare: 4.87, status: 'Lost', change: '-20' },
      { party: 'Others', seats: 0, voteShare: 12.96, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Chepauk', winner: 'M. Karunanidhi', party: 'DMK', margin: 52700 },
      { name: 'Tiruchendur', winner: 'Nedunchezhiyan', party: 'DMK', margin: 38900 },
    ],
    highlights: [
      'DMK won massive mandate with 184 seats',
      'Karunanidhi led DMK after C.N. Annadurai\'s death in 1969',
      'Congress suffered heavy defeat across Tamil Nadu',
      'Highest voter turnout at 76.6% reflecting DMK popularity',
      'DMK\'s Dravidian ideology consolidated across all districts',
    ],
  },
  1967: {
    totalSeats: 234, turnout: '76.57%', chiefMinister: 'C.N. Annadurai', rulingParty: 'DMK',
    parties: [
      { party: 'DMK+', seats: 138, voteShare: 40.69, status: 'Won', change: '+131' },
      { party: 'Congress', seats: 49, voteShare: 41.55, status: 'Lost', change: '-88' },
      { party: 'Swatantra', seats: 21, voteShare: 8.87, status: '-', change: '+21' },
      { party: 'CPI', seats: 3, voteShare: 2.44, status: '-', change: '+1' },
      { party: 'CPI(M)', seats: 3, voteShare: 1.53, status: '-', change: '+3' },
      { party: 'Others', seats: 20, voteShare: 4.92, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Kancheepuram', winner: 'C.N. Annadurai', party: 'DMK', margin: 28500 },
      { name: 'Chepauk', winner: 'M. Karunanidhi', party: 'DMK', margin: 19200 },
    ],
    highlights: [
      'Historic election — first non-Congress government in Tamil Nadu',
      'C.N. Annadurai (Anna) became CM — dawn of Dravidian politics',
      'Anti-Hindi agitation of 1965 boosted DMK massively',
      'Congress lost power in Madras State for the first time',
      'Renamed Madras State to Tamil Nadu in 1969',
      'Annadurai passed away in 1969; Karunanidhi succeeded him',
    ],
  },
  1962: {
    totalSeats: 206, turnout: '71.19%', chiefMinister: 'K. Kamaraj', rulingParty: 'Congress',
    parties: [
      { party: 'Congress', seats: 139, voteShare: 46.14, status: 'Won', change: '-12' },
      { party: 'DMK', seats: 7, voteShare: 27.08, status: 'Lost', change: '+2' },
      { party: 'CPI', seats: 2, voteShare: 4.55, status: '-', change: '-10' },
      { party: 'Swatantra', seats: 5, voteShare: 6.26, status: '-', change: '+5' },
      { party: 'PSP', seats: 2, voteShare: 2.25, status: '-', change: '+2' },
      { party: 'Others', seats: 51, voteShare: 13.72, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Virudhunagar', winner: 'K. Kamaraj', party: 'Congress', margin: 22400 },
      { name: 'Kancheepuram', winner: 'C.N. Annadurai', party: 'DMK', margin: 8900 },
    ],
    highlights: [
      'K. Kamaraj won his third consecutive term as CM',
      'Congress maintained dominance despite rising DMK challenge',
      'DMK grew in urban areas but couldn\'t break Congress rural stronghold',
      'Kamaraj\'s welfare policies and rural development were key',
      'Indo-China war created nationalist sentiment favoring Congress',
    ],
  },
  1957: {
    totalSeats: 205, turnout: '58.76%', chiefMinister: 'K. Kamaraj', rulingParty: 'Congress',
    parties: [
      { party: 'Congress', seats: 151, voteShare: 45.36, status: 'Won', change: '+3' },
      { party: 'DMK', seats: 5, voteShare: 13.81, status: 'Lost', change: '+5' },
      { party: 'CPI', seats: 12, voteShare: 7.95, status: '-', change: '+6' },
      { party: 'PSP', seats: 4, voteShare: 5.42, status: '-', change: '+4' },
      { party: 'Others', seats: 33, voteShare: 27.46, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Virudhunagar', winner: 'K. Kamaraj', party: 'Congress', margin: 18700 },
    ],
    highlights: [
      'Kamaraj consolidated Congress dominance in Madras State',
      'DMK contested assembly elections for the first time and won 5 seats',
      'C.N. Annadurai entered legislative politics',
      'CPI emerged as the main opposition with 12 seats',
      'State reorganization happened — Madras State boundaries redrawn',
      'Andhra Pradesh separated from Madras State in 1953',
    ],
  },
  1952: {
    totalSeats: 375, turnout: '58.30%', chiefMinister: 'C. Rajagopalachari', rulingParty: 'Congress',
    parties: [
      { party: 'Congress', seats: 152, voteShare: 37.10, status: 'Won', change: '0' },
      { party: 'CPI', seats: 6, voteShare: 5.32, status: '-', change: '0' },
      { party: 'Socialist', seats: 3, voteShare: 3.18, status: '-', change: '0' },
      { party: 'KMP', seats: 4, voteShare: 4.2, status: '-', change: '0' },
      { party: 'Commonweal', seats: 8, voteShare: 5.1, status: '-', change: '0' },
      { party: 'Independents', seats: 202, voteShare: 45.1, status: '-', change: '0' },
    ],
    keyConstituencies: [
      { name: 'Krishnagiri', winner: 'C. Rajagopalachari', party: 'Congress', margin: 15200 },
    ],
    highlights: [
      'First ever general election in independent India',
      'Madras State had 375 seats — covered present-day TN, AP, Karnataka parts',
      'Congress won plurality but needed support to form government',
      'C. Rajagopalachari (Rajaji) became the first elected CM of Madras State',
      'Large number of independents won — party system was still evolving',
      'Universal adult franchise exercised for the first time',
      'Dravidian movement was still in its formative stages',
    ],
  },
};

export const PARTY_HISTORY_COLORS = {
  'DMK': '#ef4444', 'DMK+': '#ef4444',
  'AIADMK': '#3b82f6', 'AIADMK+': '#3b82f6',
  'TVK': '#eab308',
  'BJP': '#f97316',
  'NTK': '#a855f7',
  'PMK': '#22c55e',
  'DMDK': '#06b6d4',
  'MNM': '#ec4899',
  'CPI(M)': '#dc2626',
  'CPI': '#b91c1c',
  'Congress': '#0ea5e9', 'Congress(I)': '#0ea5e9', 'Congress(U)': '#38bdf8',
  'TMC': '#14b8a6',
  'MDMK': '#8b5cf6',
  'Swatantra': '#d946ef',
  'Janata': '#84cc16', 'Janata Dal': '#84cc16',
  'PSP': '#f472b6',
  'Socialist': '#fb923c',
  'KMP': '#a78bfa',
  'Commonweal': '#2dd4bf',
  'Independents': '#737373',
  'Others': '#6b7280',
};
